#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

value1=1
print("\n value1: " + str(value1))
value2=2
print("\n value2: " + str(value2))
subsequentValue=0
i=0
total=0
total1=0
sumOfEvenValuedTerms=0
while value1< 4000000 and value2 < 4000000 and subsequentValue < 4000000:
    if value2%2==0 and value2<4000000:
        sumOfEvenValuedTerms=sumOfEvenValuedTerms+value2
    subsequentValue=value1+value2
    print("\nsubsequentValue:" + str(subsequentValue))
    value1=value2+subsequentValue
    print("\n value1: " + str(value1))
    value2=subsequentValue+value1
    print("\n value2: " + str(value2))
    
        
    
print(sumOfEvenValuedTerms )

#value2 is always the even one so thats why its used to add the sum of Even Valued Terms
